### ISSUE TITLE
Work with yew 0.11

### ISSUE THREAD

**Issue by netbit** [joselo/rust-crud#1]
Hi there!
Can you update the example to work with yew 0.11?
Currently the example does not work with yew version 0.11:
```
Compiling rust-crud v0.1.0 (D:\YandexDisk\rustProjects\rust-crud)
error[E0107]: wrong number of type arguments: expected 0, found 1
   --> src/model.rs:179:51
    |
179 | fn view_item((idx, item): (usize, &Item)) -> Html<Model> {
    |                                                   ^^^^^ unexpected type argument
error[E0107]: wrong number of type arguments: expected 0, found 1
   --> src/model.rs:112:26
    |
112 |   fn view(&self) -> Html<Self> {
    |                          ^^^^ unexpected type argument
error[E0107]: wrong number of type arguments: expected 0, found 1
   --> src/model.rs:154:32
    |
154 |   fn view_table(&self) -> Html<Self> {
    |                                ^^^^ unexpected type argument
error[E0107]: wrong number of type arguments: expected 0, found 1
  --> src\modal.rs:97:26
   |
97 |   fn view(&self) -> Html<Self> {
   |                          ^^^^ unexpected type argument
error: aborting due to 4 previous errors
For more information about this error, try `rustc --explain E0107`.
error: could not compile `rust-crud`.

To learn more, run the command again with --verbose.
error: build failed
```

**Comment by netbit** [comment]
I figured out how to run the example with yew 0.11, this problem is no longer relevant.
